// Generated by dts-bundle-generator v9.5.1

export declare const restApiModulesFederation: Function[];
export declare const trpcModulesFederation: import("@trpc/server").TRPCBuiltRouter<{
	ctx: {
		req: import("express").Request<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>;
		res: import("express").Response<any, Record<string, any>>;
	};
	meta: object;
	errorShape: import("@trpc/server").TRPCDefaultErrorShape;
	transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
	v1_demo: {
		mutation_demo: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				description?: string;
				title?: string;
			};
			output: {
				message?: string;
			};
			meta: object;
		}>;
		query_demo: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				id?: number;
			};
			output: {
				description?: string;
				id?: number;
				title?: string;
			};
			meta: object;
		}>;
	};
}>>;
export type TRPCAppRouter = typeof trpcModulesFederation;

export {};
