import { config } from 'dotenv';
//config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });
config({ path: `.env` });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const {
	NODE_ENV,
	PORT,
	SECRET_KEY,
	REFRESH_SECRET_KEY,
	LOG_FORMAT,
	LOG_DIR,
	ORIGIN,
	DB_HOST,
	DB_PORT,
	DB_USERNAME,
	DB_PASSWORD,
	DB_DATABASE,
	REDIS_HOST,
	REDIS_PORT,
	REDIS_PASSWORD,
	REDIS_DB,
	REDIS_USERNAME,
	RABBITMQ_URL,
	ENCRYPTION_KEY,
	RATE_LIMITER,
	GLOBAL_WINDOW_MINUTES,
	SLOW_DOWN_DELAY_AFTER_HITS,
	SLOW_DOWN_INITIAL_DELAY_MS,
	SLOW_DOWN_MAX_DELAY_MS,
	KAFKA_BROKER,
	PUSHER_APP_ID,
	PUSHER_KEY,
	PUSHER_SECRET,
	PUSHER_CLUSTER,
} = process.env;
